b2.keyId=0050844e8a3feb60000000002
b2.applicationKey=K005LMItbrsh5NsTb020XA9OOz9FnJo
b2.bucketName=restaurant-project
b2.region=us-east-005
b2.folder=contratos/
b2.prefix=contratos/
b2.endpoint=https://s3.us-east-005.backblazeb2.com

b2.publicFileEndpoint=https://f005.backblazeb2.com/file/restaurant-project/
